version: '3.7'
services:

  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: patrick
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dbdata:
    driver: local
